// src/components/Results.vue
// Results.vue

<template>
    <h2>気象データ</h2>
    <div class="results-country" v-if="country">{{ country }}</div>
    <div class="results-city" v-if="cityName">{{ cityName }}</div>
    <div class="results-temp" v-if="temperature">{{ temperature }}</div>
    <div class="results-condition" v-if="icon">
        <img :src="icon" alt="icon">
        <span>{{ conditionText }}</span>
    </div>
</template>

<script setup lang="ts">
import { toRefs } from "vue"

interface WeatherResults {
  country: string
  cityName: string
  temperature: string
  conditionText: string
  icon: string
}

interface Props {
  results: WeatherResults
}

const props = defineProps<Props>()

const { country, cityName, temperature, icon, conditionText } = toRefs(props.results)
</script>

// src/components/Results.svelte
<script lang="ts">
  interface WeatherResults {
    country: string
    cityName: string
    temperature: string
    conditionText: string
    icon: string
  }

  interface Props {
    results: WeatherResults
  }

  let { results }: Props = $props()
</script>

<h2>気象データ</h2>
{#if results.country}
  <div class="results-country">{results.country}</div>
{/if}
{#if results.cityName}
  <div class="results-city">{results.cityName}</div>
{/if}
{#if results.temperature}
  <div class="results-temp">{results.temperature}</div>
{/if}
{#if results.icon}
  <div class="results-condition">
    <img src={results.icon} alt="icon">
    <span>{results.conditionText}</span>
  </div>
{/if}
