// src/components/Results.svelte
<script lang="ts">
  interface WeatherResults {
    country: string
    cityName: string
    temperature: string
    conditionText: string
    icon: string
  }

  interface Props {
    results: WeatherResults
  }

  let { results }: Props = $props()
</script>

<h2>気象データ</h2>
{#if results.country}
  <div class="results-country">{results.country}</div>
{/if}
{#if results.cityName}
  <div class="results-city">{results.cityName}</div>
{/if}
{#if results.temperature}
  <div class="results-temp">{results.temperature}</div>
{/if}
{#if results.icon}
  <div class="results-condition">
    <img src={results.icon} alt="icon">
    <span>{results.conditionText}</span>
  </div>
{/if}

// src/components/Results.tsx
interface WeatherResults {
  country: string
  cityName: string
  temperature: string
  conditionText: string
  icon: string
}

interface ResultsProps {
  results: WeatherResults
}

function Results({ results }: ResultsProps) {
  const { country, cityName, temperature, icon, conditionText } = results

  return (
    <>
      <h2>気象データ</h2>
      {country && <div className="results-country">{country}</div>}
      {cityName && <div className="results-city">{cityName}</div>}
      {temperature && <div className="results-temp">{temperature}</div>}
      {icon && (
        <div className="results-condition">
          <img src={icon} alt="icon" />
          <span>{conditionText}</span>
        </div>
      )}
    </>
  )
}

export default Results
